### ISSUE TITLE
Problems with access to AdGuard VPN services in Russia

### ISSUE THREAD

**Issue by CATIOR** [AdguardTeam/AdGuardVPNExtension#144]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

last

### Environment

```markdown
- OS: Windows
- Browser: Google Chrome 116
```

### Issue Details

It doesn't work. It says, that I should try again later.

**Comment by alexx7311** [comment]
@CATIOR Some of our users have problems with access to the service. The problem is related to the implementation of blocking, and affects primarily mobile Internet users. If you use the AdGuard VPN browser extension, download the full-fledged AdGuard VPN client from our [website](https://adguard-vpn.info/).

Our whole team is working on this problem, and doing everything possible to make sure that VPN is available and working as efficiently as possible. However, at the moment it is difficult to guarantee the stability of the service.

You can follow the news on Telegram at https://t.me/s/adguardru
