### ISSUE TITLE
Cannot create a new meeting in Google Meet in Firefox

### ISSUE THREAD

**Issue by silvarius** [AdguardTeam/AdGuardVPNExtension#91]
Hello,

I noticed  that the installation and activation of the Adguard VPN on firefox is not compatible with google meet, even if the VPN is not active on the google meet page. Google meet returns an error when opening a video session.

 Notes:
* Adguard 1.3.42
* Firefox 109.0
* Ubuntu 22.04

**Comment by alexx7311** [comment]
Hello! We were able to reproduce the problem. Error: "Couldn't start the video call because of an error"
Steps:
1) Connect to any location in AdGuard VPN extension;
2) Open website https://meet.google.com/
3) Click "New meeting" > "Start an instant meeting"

As a temporary solution we recommend you to disable "Block WebRTC" feature in the extension settings or use another browser.
